# Generated by Django 4.2.27 on 2026-02-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="歌曲名")),
                ("artist", models.CharField(max_length=200, verbose_name="艺术家")),
                (
                    "cover",
                    models.ImageField(upload_to="thumbnails/", verbose_name="封面图"),
                ),
                (
                    "audio_file",
                    models.FileField(upload_to="music/", verbose_name="音频文件"),
                ),
                ("duration", models.IntegerField(default=0, verbose_name="时长(秒)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "音乐",
                "verbose_name_plural": "音乐库",
                "db_table": "music_tracks",
            },
        ),
    ]
